; HA overlay, to be run with inventory.ini.

[control_plane_secondary]
k8s-cp2 ansible_host=192.168.122.13 ansible_user=debian
k8s-cp3 ansible_host=192.168.122.14 ansible_user=debian

[load_balancer]
k8s-lb ansible_host=192.168.122.9 ansible_user=debian