---
- name: Prompt
  import_playbook: playbooks/prompt.yml

- name: Install kubeadm prerequisites
  import_playbook: playbooks/prerequisites.yml

- name: Setup load balancer
  import_playbook: playbooks/load-balancer.yml

- name: Setup cluster
  import_playbook: playbooks/kubernetes.yml
